/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_www_ndk_1_Hello */

#ifndef _Included_com_baidu_www_ndk_1_Hello
#define _Included_com_baidu_www_ndk_1_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_www_ndk_1_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_www_ndk_11_Hello_sayHello
        (JNIEnv *env, jclass type);

#ifdef __cplusplus
}
#endif
#endif
