/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_www_ndk_1_Copy */

#ifndef _Included_com_baidu_www_ndk_1_Copy
#define _Included_com_baidu_www_ndk_1_Copy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_www_ndk_1_Copy
 * Method:    copy
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_www_ndk_11_Copy_copy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
